#!/usr/bin/env python
import subprocess
import sys

if sys.argv[1]:
    print 'Starting bot in %s' % sys.argv[1]
    bound_json = '"coords/%s.json"' % sys.argv[1]
    subprocess.Popen('python __main__.py --coords ' + bound_json, shell=True)
else:
    subprocess.Popen('python __main__.py', shell=True)
